export enum LANGUAGE {
  ENGLISH = 'en',
}

export enum OTP_TYPE {
  EMAIL_VERIFICATION_OTP = 'EMAIL_VERIFICATION_OTP',
  PASSWORD_RESET_OTP = 'PASSWORD_RESET_OTP',
  MOBILE_VERIFICATION_OTP = 'MOBILE_VERIFICATION_OTP',
}